### ISSUE TITLE
the model always output `pregnancy` for diagnosis questions

### ISSUE THREAD

**Issue by JunMa11** [snap-stanford/med-flamingo#10]
Dear team,

Thanks for sharing the great work.

I'd like to use the model for diagnosis. Here is my prompt

`prompt = "You are a helpful medical assistant. You are being provided with images, a question about the image and an answer. Follow the examples and answer the last question. <image>Question: What is/are the structure near/in the middle of the brain? Answer: pons.<|endofchunk|><image>Question: Is there evidence of a right apical pneumothorax on this chest x-ray? Answer: yes.<|endofchunk|><image>Question: Is/Are there air in the patient's peritoneal cavity? Answer: no.<|endofchunk|><image>Question: Does the heart appear enlarged? Answer: yes.<|endofchunk|><image>Question: What side are the infarcts located? Answer: bilateral.<|endofchunk|><image>Question: Which image modality is this? Answer: mr flair.<|endofchunk|><image>Question: What is the most likely diagnosis? Answer:"
`

However, the model always outputs `pregnancy` for all kinds of CT and MR images. What should be the correct prompts for diagnosis questions?

**Comment by JunMa11** [comment]
sorry. there is a bug in my code. it has been fixed now.

**Comment by JerrryNie** [comment]
> sorry. there is a bug in my code. it has been fixed now.

Hi, I’ve also noticed that the model consistently generates identical responses, regardless of the varying images provided as input. Could you please share any insights or experiences related to similar issues you’ve encountered in your code? Your assistance would be greatly appreciated.
